import Header from "./Factory/Header/Header";
import ContainerMain from "./Factory/ContainerMain";
import ContainerMenu from "./Factory/Header/ContainerMenu";
import ContainerMinContent from "./Factory/ContainerMinContent";
import ContainerMaxContent from "./Factory/ContainerMaxContent";
import Paragraph from "./Factory/Paragraph"
import List from "./Factory/Lists";
import HeaderMount from "./assembledComponents/HeaderMount";
import ContainerRowHeader from "./Factory/Header/ContainerRowHeader";
import ContainerHalfWidthColumn from "./Factory/ContainerHalfWidthColumn";
import Button from "./Factory/Button";
import Imagens from "./Factory/Image";
import Square from "./Factory/Square";
import SectionMount from "./assembledComponents/SectionMount";
import Line from "./Factory/Line";
import HeaderMyTechs from "./Factory/HeaderMyTechs";
import SkillItens from "./assembledComponents/SkillItens";
import ContainerIcon from "./Factory/SectionSkill/ContainerIcon";
import SectionHeader from "./Factory/SectionHeader";
import ContainerMainScreenWidth from './Factory/SectionMainScreen/ContainerMainScreen'
import Main from './Screens/Main'
import ContainerImagen from './Factory/SectionMainScreen/ContainerImagen'
import NameHeader from './Factory/Header/NameHeader'
import ContainerSectionItens from './Factory/SectionMainScreen/ContainerSectionItens'
import ContainerButtonSection from './Factory/SectionMainScreen/ContainerButtonSection'
import Mytechs from './Screens/Mytechs'
import ContainerMyTechs from './Factory/Mytechs/ContainerMyTechs'
import ContainerHeaderTechs from './Factory/Mytechs/ContainerHeaderTechs'
import ContainerSkills from './Factory/SectionSkill/ContainerSkills'
import ContainerSkillItens from './Factory/SectionSkill/ContainerSkillItens'
import Together from './Screens/Together'
import ContainerTogether from './Factory/Together/ContainerTogether'
import ContainerLinks from './Factory/Together/ContainerLinks'
import WrapperLinks from './Factory/Together/WrapperLinks'
import ContainerButtonsLinks from "./assembledComponents/ContainerButtonsLinks";
import IconLinkContainer from "./Factory/Together/IconLinkContainer";
import Welcome from "../router/Welcome";
import AfroTodo from "../router/AfroTodo";
import ContainerForm from "./Factory/AfroToDo/ContainerForm";
import ContainerNoTask from "./Factory/AfroToDo/ContainerNoTask";
import NoTask from "./assembledComponents/AfroToDo/NoTask";
import ContainerAfroNoTask from "./Factory/AfroToDo/ContainerAfroNoTask";
import ContainerTask from "./Factory/AfroToDo/ContainerTask";
import ListTask from "./Factory/AfroToDo/ListTask";
export { Header,ContainerMain, ContainerMinContent, Paragraph, List, HeaderMount, ContainerRowHeader, ContainerHalfWidthColumn, ContainerMaxContent, Button, Imagens, Square, SectionMount, Line, ContainerMenu , HeaderMyTechs, SkillItens, ContainerIcon, SectionHeader, ContainerMainScreenWidth, Main, ContainerImagen, NameHeader, ContainerSectionItens, ContainerButtonSection, Mytechs, ContainerMyTechs, ContainerHeaderTechs, ContainerSkills, ContainerSkillItens, Together, ContainerTogether, ContainerLinks, WrapperLinks, ContainerButtonsLinks, IconLinkContainer, Welcome, AfroTodo, ContainerForm, ContainerNoTask, NoTask, ContainerAfroNoTask, ContainerTask, ListTask};